x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./docker/judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./docker/judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: ./docker/judge0/judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./docker/judge0/judge0.conf
    <<: *default-logging
    restart: always

  linter:
    image: alpha-dojo-linter:latest
    container_name: alpha-dojo-linter
    build:
      context: ./docker/linter
      dockerfile: ./Dockerfile
    ports:
      - ${LINTER_PORT}:${LINTER_PORT}
    environment:
      - LINTER_PORT=${LINTER_PORT} 

volumes:
  data:
