import type { Metadata } from 'next';
import './globals.css';
import { notoSansJP, roboto } from './fonts/google-fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSansJP.variable} ${roboto.variable}`}>
      <body>
        <div className="w-screen h-screen">
          <div className="w-full h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
