name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/ci-setup.yaml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yaml

  test:
    needs: setup
    uses: ./.github/workflows/test.yaml
