name: Discord Message

on:
  pull_request:
    types: [opened, review_requested]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitHub Bot"
          content: |
            A new Pull Request has been opened:
            **${{ github.event.pull_request.title }}**.
            PR Link: ${{ github.event.pull_request.html_url }}
