name: Lint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    timeout-minutes: 60
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: pnpm run lint
